// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/mutex.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_mutex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mutex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_mutex_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Request) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_proto_mutex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mutex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_proto_mutex_proto_rawDescGZIP(), []int{1}
}

func (x *Reply) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Reply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_mutex_proto protoreflect.FileDescriptor

const file_proto_mutex_proto_rawDesc = "" +
	"\n" +
	"\x11proto/mutex.proto\x12\x05mutex\";\n" +
	"\aRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"+\n" +
	"\x05Reply\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok26\n" +
	"\x05Mutex\x12-\n" +
	"\rRequestAccess\x12\x0e.mutex.Request\x1a\f.mutex.ReplyB7Z5github.com/SkootyPex/Mandatory-Activity-4/proto;protob\x06proto3"

var (
	file_proto_mutex_proto_rawDescOnce sync.Once
	file_proto_mutex_proto_rawDescData []byte
)

func file_proto_mutex_proto_rawDescGZIP() []byte {
	file_proto_mutex_proto_rawDescOnce.Do(func() {
		file_proto_mutex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mutex_proto_rawDesc), len(file_proto_mutex_proto_rawDesc)))
	})
	return file_proto_mutex_proto_rawDescData
}

var file_proto_mutex_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_mutex_proto_goTypes = []any{
	(*Request)(nil), // 0: mutex.Request
	(*Reply)(nil),   // 1: mutex.Reply
}
var file_proto_mutex_proto_depIdxs = []int32{
	0, // 0: mutex.Mutex.RequestAccess:input_type -> mutex.Request
	1, // 1: mutex.Mutex.RequestAccess:output_type -> mutex.Reply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_mutex_proto_init() }
func file_proto_mutex_proto_init() {
	if File_proto_mutex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mutex_proto_rawDesc), len(file_proto_mutex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mutex_proto_goTypes,
		DependencyIndexes: file_proto_mutex_proto_depIdxs,
		MessageInfos:      file_proto_mutex_proto_msgTypes,
	}.Build()
	File_proto_mutex_proto = out.File
	file_proto_mutex_proto_goTypes = nil
	file_proto_mutex_proto_depIdxs = nil
}
